### ISSUE TITLE
Guided simulation StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by subchannel13** [motib/erigone#2]
When running a guided simulation inside EUI on [test.txt](https://github.com/motib/erigone/files/3151728/test.txt) (renamed to .txt since GitHub doesn't allow uploading .pml) I get no steps in right hand window and there is an exception in command prompt:

Exception in thread "Thread-3" java.lang.StringIndexOutOfBoundsException: begin 104, end 92, length 117
        at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3410)
        at java.base/java.lang.String.substring(String.java:1883)
        at eui.Filter.extractBraces(Filter.java:394)
        at eui.Filter.storeVariables(Filter.java:457)
        at eui.Filter.filterSimulation(Filter.java:300)
        at eui.RunSpin$RunThread.run(RunSpin.java:138)

Unfortunately I don't have smaller example but I hope it's not too big.

**Comment by motib** [comment]
I was able to run a guided simulation, although I don't know if the output is OK, at least it didn't crash. Are you running a verification before a guided simulation? If you want to pursue this, please send screenshots of all the steps.

**Comment by subchannel13** [comment]
Sorry for a delay on this, here are screenshots:
![eui-sc1-compile](https://user-images.githubusercontent.com/4396064/57451027-5d583700-7260-11e9-9bbd-d3788cd94d73.png)
![eui-sc2-safety](https://user-images.githubusercontent.com/4396064/57451028-5d583700-7260-11e9-9c0f-719a1a21263b.png)
![eui-sc3-guided](https://user-images.githubusercontent.com/4396064/57451029-5d583700-7260-11e9-8c63-3e58b3c325dc.png)

Steps are: open file, compile button, safety button, guided button. There is no crash per se (probably worker thread crashes but the main thread survives) but there is no simulation result that demonstrates the counterexample. There is exception printout in command prompt. I don't know exactly where I've downloaded EUI from, probably from jSpin download section on Google Code. The program is started from run.bat.

**Comment by motib** [comment]
Hi Ivan,
The verification run writes a "trail file", which is then read by the guided simulation to replay the scenario. There is some inconsistency between what is written and the expected input: some string is too long. It may be caused by something unexpected in the source program or possibly by a bug in Erigone/EUI. I suggest that you check exactly which line in the trail file is causing the crash and take it from there.
Moti
